services:
  traefik:
    image: traefik:v3.0.3
    container_name: noc_traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - noc_net

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: noc_prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    networks:
      - noc_net

  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: noc_alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./infra/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - noc_net

  grafana:
    image: grafana/grafana:11.3.0
    container_name: noc_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    networks:
      - noc_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.noc.local`)
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: noc_blackbox
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - ./infra/blackbox/blackbox.yml:/etc/blackbox-exporter/config.yml:ro
    networks:
      - noc_net

  noc-api:
    build:
      context: ./backend/noc-api
    container_name: noc_api
    restart: unless-stopped
    depends_on:
      - prometheus
      - alertmanager
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=dev-noc-jwt-secret
      - JWT_ISSUER=noc-api
      - JWT_AUDIENCE=noc-wallboard
      - OPERATOR_USERNAME=admin
      - OPERATOR_PASSWORD=admin
      - PROMETHEUS_BASE_URL=http://prometheus:9090
      - ALERTMANAGER_BASE_URL=http://alertmanager:9093
    networks:
      - noc_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.nocapi.rule=Host(`api.noc.local`)
      - traefik.http.routers.nocapi.entrypoints=web
      - traefik.http.services.nocapi.loadbalancer.server.port=8080

volumes:
  prometheus_data:
  grafana_data:

networks:
  noc_net:
    driver: bridge

