import fs from "fs";
import path from "path";
import { exec } from "child_process";
import { promisify } from "util";
import { env } from "../env";

const execAsync = promisify(exec);

export type NotificationsConfig = {
  telegram: {
    enabled: boolean;
    botToken: string;
    chatId: string;
  };
  email: {
    enabled: boolean;
    to: string;
    from: string;
    smarthost: string;
    authUsername: string;
    authPassword: string;
  };
  webhook: {
    enabled: boolean;
    url: string;
  };
  route: {
    groupWait: string;
    groupInterval: string;
    repeatInterval: string;
  };
};

export type NotificationsConfigPublic = NotificationsConfig & {
  telegram: NotificationsConfig["telegram"] & { hasToken: boolean };
  email: NotificationsConfig["email"] & { hasPassword: boolean };
};

const DEFAULT: NotificationsConfig = {
  telegram: { enabled: false, botToken: "", chatId: "" },
  email: {
    enabled: false,
    to: "",
    from: "noc-alerts@local",
    smarthost: "",
    authUsername: "",
    authPassword: ""
  },
  webhook: { enabled: false, url: "" },
  route: {
    groupWait: "30s",
    groupInterval: "5m",
    repeatInterval: "3h"
  }
};

function runtimeDir(): string {
  const candidates = [
    path.join(process.cwd(), "data/runtime"),
    path.join(__dirname, "../../data/runtime"),
    "/app/data/runtime"
  ];
  for (const dir of candidates) {
    if (fs.existsSync(dir)) return dir;
  }
  const preferred = path.join(process.cwd(), "data/runtime");
  fs.mkdirSync(preferred, { recursive: true });
  return preferred;
}

function configPath(): string {
  return path.join(runtimeDir(), "notifications.json");
}

function alertmanagerPath(): string {
  return path.join(runtimeDir(), "alertmanager.yml");
}

function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

export function loadNotificationsConfig(): NotificationsConfig {
  const file = configPath();
  if (!fs.existsSync(file)) {
    saveNotificationsConfig(DEFAULT);
    return { ...DEFAULT };
  }
  return { ...DEFAULT, ...JSON.parse(fs.readFileSync(file, "utf8")) };
}

export function maskNotificationsConfig(config: NotificationsConfig): NotificationsConfigPublic {
  return {
    ...config,
    telegram: {
      ...config.telegram,
      botToken: config.telegram.botToken ? "••••••" : "",
      hasToken: Boolean(config.telegram.botToken)
    },
    email: {
      ...config.email,
      authPassword: config.email.authPassword ? "••••••" : "",
      hasPassword: Boolean(config.email.authPassword)
    }
  };
}

export function saveNotificationsConfig(config: NotificationsConfig): NotificationsConfig {
  const merged = { ...DEFAULT, ...config };
  fs.writeFileSync(configPath(), JSON.stringify(merged, null, 2) + "\n", "utf8");
  writeAlertmanagerYaml(merged);
  return merged;
}

export function writeAlertmanagerYaml(config: NotificationsConfig) {
  const receiverBlocks: string[] = [];

  if (config.telegram.enabled && config.telegram.botToken && config.telegram.chatId) {
    receiverBlocks.push(`  telegram_configs:
    - bot_token: ${yamlQuote(config.telegram.botToken)}
      chat_id: ${yamlQuote(config.telegram.chatId)}
      send_resolved: true
      parse_mode: HTML`);
  }

  if (
    config.email.enabled &&
    config.email.to &&
    config.email.smarthost
  ) {
    const auth =
      config.email.authUsername && config.email.authPassword
        ? `
      auth_username: ${yamlQuote(config.email.authUsername)}
      auth_password: ${yamlQuote(config.email.authPassword)}`
        : "";
    receiverBlocks.push(`  email_configs:
    - to: ${yamlQuote(config.email.to)}
      from: ${yamlQuote(config.email.from || "noc-alerts@local")}
      smarthost: ${yamlQuote(config.email.smarthost)}
      send_resolved: true${auth}`);
  }

  if (config.webhook.enabled && config.webhook.url) {
    receiverBlocks.push(`  webhook_configs:
    - url: ${yamlQuote(config.webhook.url)}
      send_resolved: true`);
  }

  const receiverBody =
    receiverBlocks.length > 0
      ? receiverBlocks.join("\n")
      : "  # No channels enabled — alerts are received but not delivered.";

  const yaml = `# Generated by noc-app — edit via Settings → Notifications
global:
  resolve_timeout: 5m

route:
  receiver: default
  group_by: ["alertname", "site"]
  group_wait: ${config.route.groupWait}
  group_interval: ${config.route.groupInterval}
  repeat_interval: ${config.route.repeatInterval}

receivers:
  - name: default
${receiverBody}

inhibit_rules: []
`;

  fs.writeFileSync(alertmanagerPath(), yaml, "utf8");
}

export async function applyNotificationsToAlertmanager(): Promise<{ ok: boolean; message: string }> {
  const config = loadNotificationsConfig();
  writeAlertmanagerYaml(config);
  const cmd = env.ALERTMANAGER_APPLY_CMD?.trim();
  if (!cmd) {
    return {
      ok: false,
      message:
        "Notifications saved to alertmanager.yml. Set ALERTMANAGER_APPLY_CMD (e.g. docker restart noc_alertmanager) or restart Alertmanager from Dokploy."
    };
  }
  try {
    const { stdout, stderr } = await execAsync(cmd, { timeout: 120_000 });
    return {
      ok: true,
      message: `Alertmanager apply completed. ${stdout || stderr || ""}`.trim()
    };
  } catch (e) {
    return {
      ok: false,
      message: e instanceof Error ? e.message : "Apply command failed"
    };
  }
}

export function mergeNotificationsPatch(
  current: NotificationsConfig,
  body: Partial<NotificationsConfig> & {
    telegram?: Partial<NotificationsConfig["telegram"]>;
    email?: Partial<NotificationsConfig["email"]>;
    webhook?: Partial<NotificationsConfig["webhook"]>;
    route?: Partial<NotificationsConfig["route"]>;
  }
): NotificationsConfig {
  const next: NotificationsConfig = {
    ...current,
    telegram: { ...current.telegram, ...(body.telegram ?? {}) },
    email: { ...current.email, ...(body.email ?? {}) },
    webhook: { ...current.webhook, ...(body.webhook ?? {}) },
    route: { ...current.route, ...(body.route ?? {}) }
  };

  if (body.telegram?.botToken === "••••••" || body.telegram?.botToken === "") {
    next.telegram.botToken = current.telegram.botToken;
  }
  if (body.email?.authPassword === "••••••" || body.email?.authPassword === "") {
    next.email.authPassword = current.email.authPassword;
  }

  return next;
}

// Bootstrap alertmanager.yml on module load if missing
try {
  if (!fs.existsSync(alertmanagerPath())) {
    writeAlertmanagerYaml(DEFAULT);
  }
} catch {
  /* optional during build */
}
