import fs from "fs";
import path from "path";
import { env } from "../env";

function resolveRuntimeDir(): string {
  const candidates = [
    path.join(process.cwd(), "data/runtime"),
    path.join(__dirname, "../../data/runtime"),
    "/app/data/runtime"
  ];
  for (const dir of candidates) {
    if (fs.existsSync(dir)) return dir;
  }
  const preferred = path.join(process.cwd(), "data/runtime");
  fs.mkdirSync(preferred, { recursive: true });
  return preferred;
}

export function syncWebsiteProbes(): string {
  // Lazy import avoids circular dependency with sites.ts persist()
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { getSiteList } = require("../data/sites") as typeof import("../data/sites");
  const siteList = getSiteList();

  const dir = resolveRuntimeDir();
  const file = path.join(dir, "website-probes.yml");

  const targets: Array<{ url: string; site: string; name: string }> = [];
  for (const site of siteList) {
    for (const w of site.websiteTargets ?? []) {
      if (w.url?.trim()) {
        targets.push({ url: w.url.trim(), site: site.id, name: w.name?.trim() || w.url });
      }
    }
  }

  if (targets.length === 0) {
    fs.writeFileSync(
      file,
      "# Generated by noc-app — no website targets configured\nscrape_configs: []\n",
      "utf8"
    );
    return file;
  }

  const yamlParts: string[] = ["# Generated by noc-app — do not edit manually", "scrape_configs:"];

  for (const t of targets) {
    yamlParts.push("  - job_name: blackbox-website");
    yamlParts.push("    metrics_path: /probe");
    yamlParts.push("    params:");
    yamlParts.push("      module: [http_2xx]");
    yamlParts.push("    static_configs:");
    yamlParts.push("      - targets:");
    yamlParts.push(`          - ${JSON.stringify(t.url)}`);
    yamlParts.push("        labels:");
    yamlParts.push(`          site: ${JSON.stringify(t.site)}`);
    yamlParts.push("          check: website");
    yamlParts.push(`          website_name: ${JSON.stringify(t.name)}`);
    yamlParts.push("    relabel_configs:");
    yamlParts.push("      - source_labels: [__address__]");
    yamlParts.push("        target_label: __param_target");
    yamlParts.push("      - source_labels: [__param_target]");
    yamlParts.push("        target_label: instance");
    yamlParts.push("      - target_label: __address__");
    yamlParts.push("        replacement: blackbox-exporter:9115");
  }

  fs.writeFileSync(file, yamlParts.join("\n") + "\n", "utf8");
  return file;
}

export async function reloadPrometheusScrapeConfigs(): Promise<{ ok: boolean; message: string }> {
  try {
    const url = new URL("/-/reload", env.PROMETHEUS_BASE_URL);
    const res = await fetch(url.toString(), { method: "POST" });
    if (res.ok) {
      return { ok: true, message: "Prometheus scrape configs reloaded." };
    }
    return {
      ok: false,
      message: `Prometheus reload returned ${res.status}. Restart noc_prometheus if needed.`
    };
  } catch (e) {
    return {
      ok: false,
      message: e instanceof Error ? e.message : "Prometheus reload failed"
    };
  }
}

export async function applyWebsiteProbes(): Promise<{ ok: boolean; message: string; file: string }> {
  const file = syncWebsiteProbes();
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { getSiteList } = require("../data/sites") as typeof import("../data/sites");
  const count = getSiteList().flatMap((s) => s.websiteTargets ?? []).length;
  const reload = await reloadPrometheusScrapeConfigs();
  return {
    ok: reload.ok,
    file,
    message: reload.ok
      ? `Website probes written and Prometheus reloaded (${count} targets).`
      : `Website probes written to ${file}. ${reload.message}`
  };
}
