global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: blackbox-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["blackbox-exporter:9115"]

  - job_name: blackbox-sites-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "https://example.com"
        labels:
          site: "site-1"
          check: "website"
      - targets:
          - "https://example.org"
        labels:
          site: "site-2"
          check: "website"
      - targets:
          - "https://example.net"
        labels:
          site: "site-3"
          check: "website"
      - targets:
          - "https://www.iana.org/domains/reserved"
        labels:
          site: "site-4"
          check: "website"
      - targets:
          - "https://www.cloudflare.com/"
        labels:
          site: "site-5"
          check: "website"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

