#!/usr/bin/env bash
# Generate config.alloy from devices.json + ICMP/remote_write/host base.
#
# Alloy contract: grafana/alloy:v1.5.1 ONLY
# - Never emit config_merge_strategy (unsupported on 1.5.1)
# - Always emit numeric scrape_interval (e.g. "15s"), never ${SCRAPE_INTERVAL_SEC}
# - SNMP uses full snmp.yml (auths + if_mib metrics) mounted beside config.alloy
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVICES_FILE="${1:-$SCRIPT_DIR/devices.json}"
OUT_FILE="${2:-$SCRIPT_DIR/config.alloy}"
# Must stay ≤30s (repo default 15s). 60s + 45s NOC freshness = false uplink downs.
SCRAPE_INTERVAL_SEC="${SCRAPE_INTERVAL_SEC:-15}"
# Alloy needs a real duration (e.g. 15s), not a shell placeholder
if ! [[ "$SCRAPE_INTERVAL_SEC" =~ ^[0-9]+$ ]]; then
  SCRAPE_INTERVAL_SEC=15
fi

validate_out() {
  if [[ -x "$SCRIPT_DIR/validate-config.sh" ]]; then
    "$SCRIPT_DIR/validate-config.sh" "$OUT_FILE"
  elif [[ -f "$SCRIPT_DIR/validate-config.sh" ]]; then
    bash "$SCRIPT_DIR/validate-config.sh" "$OUT_FILE"
  else
    # Inline fail-closed if validate script missing on NUC
    if grep -qE '\$\{[A-Za-z0-9_]+\}' "$OUT_FILE"; then
      echo "ERROR: config.alloy still contains unexpanded \${...}" >&2
      exit 1
    fi
    if grep -qE '^[[:space:]]*config_merge_strategy[[:space:]]*=' "$OUT_FILE"; then
      echo "ERROR: config_merge_strategy not supported on Alloy v1.5.1" >&2
      exit 1
    fi
    if ! grep -qE 'scrape_interval = "[0-9]+s"' "$OUT_FILE"; then
      echo "ERROR: config.alloy missing numeric scrape_interval" >&2
      exit 1
    fi
  fi
}

if [[ ! -f "$DEVICES_FILE" ]]; then
  echo "[]" > "$DEVICES_FILE"
fi

# Unquoted EOF so SCRAPE_INTERVAL_SEC expands; Alloy sys.env(...) has no bash $.
cat > "$OUT_FILE" <<EOF
// Generated by generate-config.sh — re-run after editing devices.json
//
// Required env:
//   CENTRAL_REMOTE_WRITE_URL, CF_ACCESS_CLIENT_ID, CF_ACCESS_CLIENT_SECRET
//   SITE_NAME, PING_TARGET_1, PING_TARGET_2, HOST_DEVICE_ID

prometheus.remote_write "central" {
  endpoint {
    url = sys.env("CENTRAL_REMOTE_WRITE_URL")

    headers = {
      "CF-Access-Client-Id"     = sys.env("CF_ACCESS_CLIENT_ID"),
      "CF-Access-Client-Secret" = sys.env("CF_ACCESS_CLIENT_SECRET"),
    }
  }
}

prometheus.exporter.blackbox "icmp_probe" {
  config_file = "blackbox.yml"

  target {
    name    = "ping_dns"
    address = sys.env("PING_TARGET_1")
    module  = "icmp"
    labels  = { check = "wan_dns", site = sys.env("SITE_NAME") }
  }

  target {
    name    = "ping_vps"
    address = sys.env("PING_TARGET_2")
    module  = "icmp"
    labels  = { check = "wan_vps", site = sys.env("SITE_NAME") }
  }
}

prometheus.scrape "icmp_scrape" {
  targets    = prometheus.exporter.blackbox.icmp_probe.targets
  forward_to = [prometheus.remote_write.central.receiver]
  job_name   = "site_icmp_probe"
  scrape_interval = "${SCRAPE_INTERVAL_SEC}s"
}

prometheus.exporter.unix "nuc_host" {
  procfs_path = "/rootfs/proc"
  sysfs_path  = "/rootfs/sys"
  rootfs_path = "/rootfs"

  disable_collectors = ["ipvs", "btrfs", "infiniband", "xfs", "zfs"]

  filesystem {
    fs_types_exclude     = "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|tmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
    mount_points_exclude = "^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)($|/)"
  }
}

discovery.relabel "nuc_host" {
  targets = prometheus.exporter.unix.nuc_host.targets

  rule {
    target_label = "site"
    replacement  = sys.env("SITE_NAME")
  }

  rule {
    target_label = "device"
    replacement  = sys.env("HOST_DEVICE_ID")
  }

  rule {
    target_label = "role"
    replacement  = "site-box"
  }
}

prometheus.scrape "nuc_host_scrape" {
  targets         = discovery.relabel.nuc_host.output
  forward_to      = [prometheus.remote_write.central.receiver]
  job_name        = "site_host"
  scrape_interval = "${SCRAPE_INTERVAL_SEC}s"
}
EOF

DEVICE_COUNT="$(python3 -c "import json; print(len(json.load(open('$DEVICES_FILE', encoding='utf-8-sig'))))" 2>/dev/null || echo 0)"

SNMP_YML="${SCRIPT_DIR}/snmp.yml"
# Site-wide default; per-device snmpCommunity in devices.json overrides in generated auths.
SNMP_DEFAULT_COMMUNITY="${SNMP_DEFAULT_COMMUNITY:-}"

if [[ "$DEVICE_COUNT" -eq 0 ]]; then
  echo "// No SNMP devices in devices.json." >> "$OUT_FILE"
  validate_out
  echo "Wrote $OUT_FILE (ICMP + host metrics; no SNMP)"
  exit 0
fi

# Rebuild snmp.yml auths (default_v2 + auth_<deviceId>) and emit Alloy targets with matching auth.
export SCRAPE_INTERVAL_SEC
python3 - "$DEVICES_FILE" "$SNMP_YML" "$SNMP_DEFAULT_COMMUNITY" "$SCRAPE_INTERVAL_SEC" >> "$OUT_FILE" <<'PY'
import json, sys, re, os

devices_path, snmp_path, default_arg, scrape_sec = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
devices = json.load(open(devices_path, encoding="utf-8-sig"))

def safe(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", s)

def yaml_escape(s: str) -> str:
    if re.search(r'[:#{}\[\],&*?|>!%@`]', s) or s != s.strip() or s in ("", "true", "false", "null"):
        return json.dumps(s)
    return s

# Resolve site default community
default = (default_arg or os.environ.get("SNMP_DEFAULT_COMMUNITY") or "").strip()
if not default and os.path.isfile(snmp_path):
    text = open(snmp_path, encoding="utf-8").read()
    m = re.search(r"default_v2:\s*\n\s*community:\s*(.+)", text)
    if not m:
        m = re.search(r"public_v2:\s*\n\s*community:\s*(.+)", text)
    if m:
        default = m.group(1).strip().strip('"').strip("'")
if not default:
    default = "public"

if not re.fullmatch(r"[0-9]+", scrape_sec or ""):
    scrape_sec = "15"

# Preserve modules: from existing snmp.yml after "modules:"
modules_block = ""
if os.path.isfile(snmp_path):
    text = open(snmp_path, encoding="utf-8").read()
    idx = text.find("\nmodules:")
    if idx == -1:
        idx = text.find("modules:")
    if idx != -1:
        modules_block = text[idx:].lstrip("\n")
        if not modules_block.startswith("modules:"):
            modules_block = "modules:" + modules_block.split("modules:", 1)[-1]

if not modules_block.strip():
    modules_block = """modules:
  if_mib:
    walk:
      - 1.3.6.1.2.1.2.2.1.2
      - 1.3.6.1.2.1.2.2.1.8
      - 1.3.6.1.2.1.2.2.1.5
      - 1.3.6.1.2.1.31.1.1.1.1
      - 1.3.6.1.2.1.31.1.1.1.6
      - 1.3.6.1.2.1.31.1.1.1.10
    metrics:
      - name: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: DisplayString
        help: A textual description of the interface
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifOperStatus
        oid: 1.3.6.1.2.1.2.2.1.8
        type: gauge
        help: The current operational state of the interface
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifSpeed
        oid: 1.3.6.1.2.1.2.2.1.5
        type: gauge
        help: Estimate of the interface bandwidth in bits per second
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifName
        oid: 1.3.6.1.2.1.31.1.1.1.1
        type: DisplayString
        help: Interface name
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifHCInOctets
        oid: 1.3.6.1.2.1.31.1.1.1.6
        type: counter
        help: The total number of octets received on the interface
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifHCOutOctets
        oid: 1.3.6.1.2.1.31.1.1.1.10
        type: counter
        help: The total number of octets transmitted out of the interface
        indexes:
          - labelname: ifIndex
            type: gauge
"""

auth_lines = [
    "# Generated by generate-config.sh — per-device auths + site default.",
    "# Contract: grafana/alloy:v1.5.1 — do not add config_merge_strategy.",
    "# default_v2 = Console Setup community; auth_<id> = device snmpCommunity or default.",
    "",
    "auths:",
    "  default_v2:",
    f"    community: {yaml_escape(default)}",
    "    security_level: noAuthNoPriv",
    "    version: 2",
    "  public_v2:",
    f"    community: {yaml_escape(default)}",
    "    security_level: noAuthNoPriv",
    "    version: 2",
]

for d in devices:
    tid = safe(d["id"])
    community = (d.get("snmpCommunity") or "").strip() or default
    auth_lines += [
        f"  auth_{tid}:",
        f"    community: {yaml_escape(community)}",
        "    security_level: noAuthNoPriv",
        "    version: 2",
    ]

open(snmp_path, "w", encoding="utf-8").write("\n".join(auth_lines) + "\n\n" + modules_block.rstrip() + "\n")

# Emit Alloy SNMP block to stdout (appended to config.alloy by shell)
print()
print('prometheus.exporter.snmp "site_devices" {')
print('  // Alloy v1.5.1: full snmp.yml — per-device auth_* from devices.json')
print('  config_file = "snmp.yml"')
print()

for d in devices:
    tid = safe(d["id"])
    ip = d["snmpIp"].replace('"', '\\"')
    did = d["id"].replace('"', '\\"')
    vendor = d.get("vendor", "generic").replace('"', '\\"')
    print(f'  target "{tid}" {{')
    print(f'    address = "{ip}"')
    print(f'    module  = "if_mib"')
    print(f'    auth    = "auth_{tid}"')
    print(f'    labels  = {{')
    print(f'      site   = sys.env("SITE_NAME"),')
    print(f'      device = "{did}",')
    print(f'      vendor = "{vendor}",')
    print(f'    }}')
    print(f'  }}')
    print()

print("}")
print()
# Alloy prometheus.exporter.snmp sets job = "integrations/snmp" + "/" + target_name
# (Agent-compatible). scrape job_name is ignored when job is already set — without
# relabel, Prometheus never sees job=site_snmp_if_mib and NOC looks "broken".
print('discovery.relabel "snmp_job" {')
print("  targets = prometheus.exporter.snmp.site_devices.targets")
print()
print("  rule {")
print('    target_label = "job"')
print('    replacement  = "site_snmp_if_mib"')
print("  }")
print("}")
print()
print('prometheus.scrape "snmp_scrape" {')
print("  targets         = discovery.relabel.snmp_job.output")
print("  forward_to      = [prometheus.relabel.snmp_canonical.receiver]")
print('  job_name        = "site_snmp_if_mib"')
print(f'  scrape_interval = "{scrape_sec}s"')
print("}")
print()
print('prometheus.relabel "snmp_canonical" {')
print("  forward_to = [prometheus.remote_write.central.receiver]")
print()
print("  rule {")
print('    action       = "replace"')
print('    target_label = "job"')
print('    replacement  = "site_snmp_if_mib"')
print("  }")
print("}")
PY

validate_out
echo "Wrote $OUT_FILE (ICMP + host + $DEVICE_COUNT SNMP device(s)); updated $SNMP_YML auths"
