#!/usr/bin/env bash
# Generate config.alloy from devices.json + ICMP/remote_write/host base.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVICES_FILE="${1:-$SCRIPT_DIR/devices.json}"
OUT_FILE="${2:-$SCRIPT_DIR/config.alloy}"
SCRAPE_INTERVAL_SEC="${SCRAPE_INTERVAL_SEC:-60}"

if [[ ! -f "$DEVICES_FILE" ]]; then
  echo "[]" > "$DEVICES_FILE"
fi

cat > "$OUT_FILE" <<'EOF'
// Generated by generate-config.sh — re-run after editing devices.json
//
// Required env:
//   CENTRAL_REMOTE_WRITE_URL, CF_ACCESS_CLIENT_ID, CF_ACCESS_CLIENT_SECRET
//   SITE_NAME, PING_TARGET_1, PING_TARGET_2, HOST_DEVICE_ID

prometheus.remote_write "central" {
  endpoint {
    url = sys.env("CENTRAL_REMOTE_WRITE_URL")

    headers = {
      "CF-Access-Client-Id"     = sys.env("CF_ACCESS_CLIENT_ID"),
      "CF-Access-Client-Secret" = sys.env("CF_ACCESS_CLIENT_SECRET"),
    }
  }
}

prometheus.exporter.blackbox "icmp_probe" {
  config_file = "blackbox.yml"

  target {
    name    = "ping_dns"
    address = sys.env("PING_TARGET_1")
    module  = "icmp"
    labels  = { check = "wan_dns", site = sys.env("SITE_NAME") }
  }

  target {
    name    = "ping_vps"
    address = sys.env("PING_TARGET_2")
    module  = "icmp"
    labels  = { check = "wan_vps", site = sys.env("SITE_NAME") }
  }
}

prometheus.scrape "icmp_scrape" {
  targets    = prometheus.exporter.blackbox.icmp_probe.targets
  forward_to = [prometheus.remote_write.central.receiver]
  job_name   = "site_icmp_probe"
  scrape_interval = "${SCRAPE_INTERVAL_SEC}s"
}

prometheus.exporter.unix "nuc_host" {
  procfs_path = "/rootfs/proc"
  sysfs_path  = "/rootfs/sys"
  rootfs_path = "/rootfs"

  disable_collectors = ["ipvs", "btrfs", "infiniband", "xfs", "zfs"]

  filesystem {
    fs_types_exclude     = "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|tmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
    mount_points_exclude = "^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)($|/)"
  }
}

discovery.relabel "nuc_host" {
  targets = prometheus.exporter.unix.nuc_host.targets

  rule {
    target_label = "site"
    replacement  = sys.env("SITE_NAME")
  }

  rule {
    target_label = "device"
    replacement  = sys.env("HOST_DEVICE_ID")
  }

  rule {
    target_label = "role"
    replacement  = "site-box"
  }
}

prometheus.scrape "nuc_host_scrape" {
  targets         = discovery.relabel.nuc_host.output
  forward_to      = [prometheus.remote_write.central.receiver]
  job_name        = "site_host"
  scrape_interval = "${SCRAPE_INTERVAL_SEC}s"
}
EOF

DEVICE_COUNT="$(python3 -c "import json; print(len(json.load(open('$DEVICES_FILE'))))" 2>/dev/null || echo 0)"

if [[ "$DEVICE_COUNT" -eq 0 ]]; then
  echo "// No SNMP devices in devices.json." >> "$OUT_FILE"
  echo "Wrote $OUT_FILE (ICMP + host metrics; no SNMP)"
  exit 0
fi

{
  echo ""
  echo "prometheus.exporter.snmp \"site_devices\" {"
  echo "  config_file = \"snmp.yml\""
  echo ""
} >> "$OUT_FILE"

python3 - "$DEVICES_FILE" >> "$OUT_FILE" <<'PY'
import json, sys, re

path = sys.argv[1]
devices = json.load(open(path))

def safe(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", s)

for d in devices:
    tid = safe(d["id"])
    ip = d["snmpIp"].replace('"', '\\"')
    did = d["id"].replace('"', '\\"')
    vendor = d.get("vendor", "generic").replace('"', '\\"')
    print(f'  target "{tid}" {{')
    print(f'    address = "{ip}"')
    print(f'    module  = "if_mib"')
    print(f'    auth    = "public_v2"')
    print(f'    labels  = {{')
    print(f'      site   = sys.env("SITE_NAME"),')
    print(f'      device = "{did}",')
    print(f'      vendor = "{vendor}",')
    print(f'    }}')
    print(f'  }}')
    print()
PY

{
  echo "}"
  echo ""
  echo "prometheus.scrape \"snmp_scrape\" {"
  echo "  targets    = prometheus.exporter.snmp.site_devices.targets"
  echo "  forward_to = [prometheus.remote_write.central.receiver]"
  echo "  job_name   = \"site_snmp_if_mib\""
  echo "  scrape_interval = \"${SCRAPE_INTERVAL_SEC}s\""
  echo "}"
} >> "$OUT_FILE"

echo "Wrote $OUT_FILE (ICMP + host + $DEVICE_COUNT SNMP device(s))"
