#!/usr/bin/env bash
# Generate config.alloy from devices.json + ICMP/remote_write base.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVICES_FILE="${1:-$SCRIPT_DIR/devices.json}"
OUT_FILE="${2:-$SCRIPT_DIR/config.alloy}"

if [[ ! -f "$DEVICES_FILE" ]]; then
  echo "[]" > "$DEVICES_FILE"
fi

SITE_ENV='sys.env("SITE_NAME")'

cat > "$OUT_FILE" <<'EOF'
// Generated by generate-config.sh — re-run after editing devices.json
//
// Required env:
//   CENTRAL_REMOTE_WRITE_URL, CF_ACCESS_CLIENT_ID, CF_ACCESS_CLIENT_SECRET
//   SITE_NAME, PING_TARGET_1, PING_TARGET_2

prometheus.remote_write "central" {
  endpoint {
    url = sys.env("CENTRAL_REMOTE_WRITE_URL")

    headers = {
      "CF-Access-Client-Id"     = sys.env("CF_ACCESS_CLIENT_ID"),
      "CF-Access-Client-Secret" = sys.env("CF_ACCESS_CLIENT_SECRET"),
    }
  }
}

prometheus.exporter.blackbox "icmp_probe" {
  config_file = "blackbox.yml"

  target {
    name    = "ping_dns"
    address = sys.env("PING_TARGET_1")
    module  = "icmp"
    labels  = { check = "wan_dns", site = sys.env("SITE_NAME") }
  }

  target {
    name    = "ping_vps"
    address = sys.env("PING_TARGET_2")
    module  = "icmp"
    labels  = { check = "wan_vps", site = sys.env("SITE_NAME") }
  }
}

prometheus.scrape "icmp_scrape" {
  targets    = prometheus.exporter.blackbox.icmp_probe.targets
  forward_to = [prometheus.remote_write.central.receiver]
  job_name   = "site_icmp_probe"
}
EOF

DEVICE_COUNT="$(python3 -c "import json; print(len(json.load(open('$DEVICES_FILE'))))" 2>/dev/null || echo 0)"

if [[ "$DEVICE_COUNT" -eq 0 ]]; then
  echo "// No SNMP devices in devices.json (ICMP-only)." >> "$OUT_FILE"
  echo "Wrote $OUT_FILE (ICMP only)"
  exit 0
fi

{
  echo ""
  echo "prometheus.exporter.snmp \"site_devices\" {"
  echo "  config_file = \"snmp.yml\""
  echo ""
} >> "$OUT_FILE"

python3 - "$DEVICES_FILE" >> "$OUT_FILE" <<'PY'
import json, sys, re

path = sys.argv[1]
devices = json.load(open(path))

def safe(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", s)

for d in devices:
    tid = safe(d["id"])
    ip = d["snmpIp"].replace('"', '\\"')
    did = d["id"].replace('"', '\\"')
    vendor = d.get("vendor", "generic").replace('"', '\\"')
    print(f'  target "{tid}" {{')
    print(f'    address = "{ip}"')
    print(f'    module  = "if_mib"')
    print(f'    auth    = "public_v2"')
    print(f'    labels  = {{')
    print(f'      site   = sys.env("SITE_NAME"),')
    print(f'      device = "{did}",')
    print(f'      vendor = "{vendor}",')
    print(f'    }}')
    print(f'  }}')
    print()
PY

{
  echo "}"
  echo ""
  echo "prometheus.scrape \"snmp_scrape\" {"
  echo "  targets    = prometheus.exporter.snmp.site_devices.targets"
  echo "  forward_to = [prometheus.remote_write.central.receiver]"
  echo "  job_name   = \"site_snmp_if_mib\""
  echo "}"
} >> "$OUT_FILE"

echo "Wrote $OUT_FILE ($DEVICE_COUNT SNMP device(s))"
